### PR TITLE
Upgrade to `syn` 2.0

### LINKED ISSUE #208: Bump `syn` ^2
`syn` has bumped to ^2 - perhaps a a good idea to bump here `rust-embed-impl` as well

https://github.com/dtolnay/syn/releases/tag/2.0.0

### PR DESCRIPTION
**Pull request by smoelius**
Resolves #208

I think I did this right, but please scrutinize.

### CODE REVIEW

**Review by AzureMarker — APPROVED** [review]

**Comment by pyrossh** [comment]
@smoelius thanks.

**Comment by smoelius** [comment]
Do you think it would be possible to get a release with this change?

For [one of my projects](https://github.com/trailofbits/dylint), `rust-embed-impl v6.5.0` is the last dependency that uses `syn` 1.0.

**Comment by pyrossh** [comment]
Yep will push a release was just too lazy to do it.

**Comment by pyrossh** [comment]
v6.7.0 released

**Pull request merged**
