### PR TITLE
Add is_dir helper function to metadata

### PR DESCRIPTION
**Pull request by jaztec**
Jumping on #170, adding an `is_dir` helper function based on fs metadata.

### CODE REVIEW

**Comment by jaztec** [comment]
Workflow is fixed: https://github.com/jaztec/rust-embed/actions/runs/3504800911

**Comment by pyrossh** [comment]
LGTM

**Comment by jaztec** [comment]
I've been writing some tests and noticed it is not possible to fetch a folder anyway. That does make this PR a tad useless.

I could extend https://github.com/pyrossh/rust-embed/blob/master/utils/src/lib.rs#L111 a bit to also read a folder but I'm not sure what behavior should be displayed and/or what usecase it would fullfill.

**Comment by pyrossh** [comment]
Yes I was wondering that. I thought it could be useful to do some recursive stuff. Or maybe get a default `index.html` if the path is folder. Example use case would be something like hosting a website using a static site generator like hugo.

**Comment by jaztec** [comment]
I updated the function, it will now read the directory metadata but keeps a clear `Vec<u8>` for data, hash will be empty as well.

**Comment by jaztec** [comment]
> Yes I was wondering that. I thought it could be useful to do some recursive stuff. Or maybe get a default `index.html` if the path is folder. Example use case would be something like hosting a website using a static site generator like hugo.

Fetching an `index.html` would be interesting as well. Altough it might a bit "magical" what happens under the hood, maybe adding a `default_file` function could make the behavior and intend more clear?

**Comment by pyrossh** [comment]
I would leave that upto the user to implement it in the web framework of their choice, as its a specific scenario that only applies to JAM stack based websites.

**Comment by jaztec** [comment]
I fixed the BC break issue by the way, I scr*wed up big time there. https://github.com/jaztec/rust-embed/commit/13fabb9ba65d3d84e154ab43d3081a498956786c

However the branch still doesn't add any real value. I would like to extend a next PR to actually include folders as new root elements. So you can use something like `let new_root = Asset::get('path/to/folder'); root.get('file.html')`.

So it can be an actual BC breaking version bump.

**Comment by jaztec** [comment]
> I guess instead of overriding the Asset::get function you could have another function Asset::folder which returns the instance of the folder

True, that would not cause a break.

> But do you have any use cases for this? I haven't see this used in the wild though.

I was thinking of a usecase I once build in Go, it was a project which used a rule engine to handle incoming requests based on hostname and path. It would either proxy a placeholder, redirect to a marketing site or dynamically load a SPA website if it was present.

But thinking again I recon the entire purpose of the library is loading from embedded files, thus files known at compile time. When I got the assets at compile time there is no need anymore to load them dynamically I guess.

You want me to make a safe PR for the `is_dir` helper? The `iter` will only return actual files, only the `get` will return a EmbeddedFile with an optional `is_dir: true`.

**Comment by AzureMarker** [comment]
> > I guess instead of overriding the Asset::get function you could have another function Asset::folder which returns the instance of the folder
> 
> True, that would not cause a break.

This is still a breaking change unless the new trait function has a default implementation. It's possible for users to implement RustEmbed on their own types (ex. to mock it).

**Comment by jaztec** [comment]
> This is still a breaking change unless the new trait function has a default implementation. It's possible for users to implement RustEmbed on their own types (ex. to mock it).

True again, from a different participator this time. I actually don't think having dynamic folders is usefull anymore, just because my last comment as a whole. At compile time you are aware of the folders included and so you can embed them at your own discretion. Having it be loaded dynamically doesn't add any value.

My only question now is; do I submit a new PR for this
> You want me to make a safe PR for the is_dir helper? The iter will only return actual files, only the get will return a EmbeddedFile with an optional is_dir: true.

Based on this: https://github.com/jaztec/rust-embed/commit/13fabb9ba65d3d84e154ab43d3081a498956786c

**Comment by AzureMarker** [comment]
I think we need to understand the use case behind #170 before doing any implementation.

**Comment by jaztec** [comment]
Let's open it up then. I can't so be my guest

**Pull request merged**
